package events

type Event string

const (
	Reconnect                     Event = "RECONNECT"
	ChannelCreate                 Event = "CHANNEL_CREATE"
	ChannelUpdate                 Event = "CHANNEL_UPDATE"
	ChannelDelete                 Event = "CHANNEL_DELETE"
	ChannelPinsUpdate             Event = "CHANNEL_PINS_UPDATE"
	ThreadCreate                  Event = "THREAD_CREATE"
	ThreadUpdate                  Event = "THREAD_UPDATE"
	ThreadDelete                  Event = "THREAD_DELETE"
	ThreadListSync                Event = "THREAD_LIST_SYNC"
	ThreadMemberUpdate            Event = "THREAD_MEMBER_UPDATE"
	ThreadMembersUpdate           Event = "THREAD_MEMBERS_UPDATE"
	GuildCreate                   Event = "GUILD_CREATE"
	GuildUpdate                   Event = "GUILD_UPDATE"
	GuildDelete                   Event = "GUILD_DELETE"
	GuildBanAdd                   Event = "GUILD_BAN_ADD"
	GuildBanRemove                Event = "GUILD_BAN_REMOVE"
	GuildEmojisUpdate             Event = "GUILD_EMOJIS_UPDATE"
	GuildStickersUpdate           Event = "GUILD_STICKERS_UPDATE"
	GuildIntegrationsUpdate       Event = "GUILD_INTEGRATIONS_UPDATE"
	GuildMemberAdd                Event = "GUILD_MEMBER_ADD"
	GuildMemberRemove             Event = "GUILD_MEMBER_REMOVE"
	GuildMemberUpdate             Event = "GUILD_MEMBER_UPDATE"
	GuildMembersChunk             Event = "GUILD_MEMBERS_CHUNK"
	GuildRoleCreate               Event = "GUILD_ROLE_CREATE"
	GuildRoleUpdate               Event = "GUILD_ROLE_UPDATE"
	GuildRoleDelete               Event = "GUILD_ROLE_DELETE"
	GuildScheduledEventCreate     Event = "GUILD_SCHEDULED_EVENT_CREATE"
	GuildScheduledEventUpdate     Event = "GUILD_SCHEDULED_EVENT_UPDATE"
	GuildScheduledEventDelete     Event = "GUILD_SCHEDULED_EVENT_DELETE"
	GuildScheduledEventUserAdd    Event = "GUILD_SCHEDULED_EVENT_USER_ADD"
	GuildScheduledEventUserRemove Event = "GUILD_SCHEDULED_EVENT_USER_REMOVE"
	IntegrationCreate             Event = "INTEGRATION_CREATE"
	IntegrationUpdate             Event = "INTEGRATION_UPDATE"
	IntegrationDelete             Event = "INTEGRATION_DELETE"
	InteractionCreate             Event = "INTERACTION_CREATE"
	InviteCreate                  Event = "INVITE_CREATE"
	InviteDelete                  Event = "INVITE_DELETE"
	MessageCreate                 Event = "MESSAGE_CREATE"
	MessageUpdate                 Event = "MESSAGE_UPDATE"
	MessageDelete                 Event = "MESSAGE_DELETE"
	MessageDeleteBulk             Event = "MESSAGE_DELETE_BULK"
	MessageReactionAdd            Event = "MESSAGE_REACTION_ADD"
	MessageReactionRemove         Event = "MESSAGE_REACTION_REMOVE"
	MessageReactionRemoveAll      Event = "MESSAGE_REACTION_REMOVE_ALL"
	MessageReactionRemoveEmoji    Event = "MESSAGE_REACTION_REMOVE_EMOJI"
	PresenceUpdate                Event = "PRESENCE_UPDATE"
	StageInstanceCreate           Event = "STAGE_INSTANCE_CREATE"
	StageInstanceUpdate           Event = "STAGE_INSTANCE_UPDATE"
	StageInstanceDelete           Event = "STAGE_INSTANCE_DELETE"
	TypingStart                   Event = "TYPING_START"
	UserUpdate                    Event = "USER_UPDATE"
	VoiceStateUpdate              Event = "VOICE_STATE_UPDATE"
	VoiceServerUpdate             Event = "VOICE_SERVER_UPDATE"
	WebhooksUpdate                Event = "WEBHOOKS_UPDATE"

	ShardReady             Event = "READY"
	ShardDisconnected      Event = "INTERNAL_SHARD_DISCONNECTED"
	ShardResumed           Event = "RESUMED"
	ShardPrefetchCompleted Event = "INTERNAL_SHARD_PREFETCH_COMPLETED"
)
